### ISSUE TITLE
crash in fragment

### ISSUE THREAD

**Issue by anidmurmu** [MapmyIndia/mapmyindia-maps-vectorSDK-android#3]
[map.zip](https://github.com/MapmyIndia/mapmyindia-maps-vectorSDK-android/files/5090305/map.zip) (Please download the zip file for reproducting the issue)
Hi Team,
 I have got an issue with mapmyindia integration. I would like to know the fixes for this.

 Here are my scenarios.

First issue

 1) In launcher activity(MainActivity) I have a fragment(FirstFragment) which contains a button to navigate to the next fragment(SecondFragment) which contains MapView.

 2) When I am in SecondFragment and click back button,  app freezes and then closes after some time.

 Second issue

 1) In SecondFragment when MapView in xml is not referenced from fragment, then on click back, app doesn't freeze but going to SecondFragment more than once and then coming back to Fragment causes the app crash.

Note

 Here the above scenario mentioned when implemented using NavGraph, issue remains the same

**Comment by Saksham66** [comment]
@anidmurmu 
Please add below line in your xml file where you declaring the mapview than try
        
app:mapbox_renderTextureMode="true"

**Comment by anidmurmu** [comment]
Hi @Saksham66 , 
The fix given above seems to be working fine.  I will update again, once it has been tested by QA team.
Thanks for the quick response and solution.
