### ISSUE TITLE
Illegal invoke-super to int com.mmi.apis.utils.c.c() from class com.mmi.b.g   (.apk not  create)

### ISSUE THREAD

**Issue by Guruvendra** [MapmyIndia/mapmyindia-maps-vectorSDK-android#4]
`buildscript
        {
            repositories {
                maven {
                    url 'https://maven.fabric.io/public'
                }
            }
            dependencies
                    {
                        classpath 'io.fabric.tools:gradle:1.+'
                    }
        }

apply plugin: 'com.android.application'
apply plugin: 'io.fabric'
repositories { maven { url 'https://maven.fabric.io/public' } }
android {
    compileSdkVersion 29
    buildToolsVersion '29.0.1'
    defaultConfig {
        applicationId "xxxx.xxxxx.xxxx"
        minSdkVersion 21
        targetSdkVersion 29
        versionCode 2014
        versionName "2020.7.6"
        multiDexEnabled true
        proguardFiles getDefaultProguardFile('proguard-android.txt')
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        ndk {
            abiFilters "armeabi"
        }

    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
     

    dexOptions {
        javaMaxHeapSize "4g" //specify the heap size for the dex process
        preDexLibraries = true  //delete the already predexed libraries
    }
    buildTypes {
        release {

            //  debuggable true
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            ext.enableCrashlytics = true
            // multiDexKeepProguard file('proguard-rules.pro')
            multiDexEnabled = true
            //  signingConfig signingConfigs.release
        }
        debug {
            debuggable true
             shrinkResources true
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            ext.enableCrashlytics = true
            //multiDexKeepProguard file('proguard-rules.pro')
            // signingConfig signingConfigs.release
        }
    }

    packagingOptions {
        exclude 'META-INF/rxjava.properties'
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/proguard/androidx-annotations.pro'
    }

    lintOptions {
        checkReleaseBuilds false
        // Or, if you prefer, you can continue to check for errors in release builds,
        // but continue the build even when errors are found:
        abortOnError false
    }
}
repositories {
    mavenCentral()
    mavenLocal()
    jcenter()

    maven {
        url 'https://oss.sonatype.org/content/repositories/snapshots/'
        name 'OSS-Sonatype'
    }
    maven {
        url "https://jitpack.io"
    }
    flatDir {
        dirs 'libs'
    }
    maven {
        url 'https://maven.google.com/'
        name 'Google'
    }
}
dependencies {
    testImplementation 'junit:junit:4.12'
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation project(':library')
    implementation files('libs/aws-android-sdk-core-2.4.7.jar')

    implementation files('libs/httpmime-4.3.6.jar')
    implementation files('libs/httpclient-4.3.6.jar')
    implementation files('libs/httpcore-4.3.3.jar')

    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'androidx.legacy:legacy-support-v13:1.0.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.browser:browser:1.2.0'
    implementation 'androidx.annotation:annotation:1.1.0'
    implementation('com.google.android.gms:play-services-maps:17.0.0')
    implementation('com.google.android.gms:play-services-base:17.3.0')
    implementation('com.google.android.gms:play-services-auth:18.1.0')
    implementation('com.google.android.gms:play-services-gcm:17.0.0')
    implementation('com.google.android.gms:play-services-location:17.0.0')
    implementation 'com.fxn769:oblique:2.0'
    implementation 'com.fxn769:ariana:1.0'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'androidx.recyclerview:recyclerview:1.0.0'
    implementation 'com.google.firebase:firebase-core:16.0.7'
    implementation 'com.google.firebase:firebase-messaging:17.3.0'
    implementation 'com.google.firebase:firebase-analytics:16.0.3'
    implementation 'com.crashlytics.sdk.android:crashlytics:2.10.1'
    implementation group: 'androidx.cardview', name: 'cardview', version: '1.0.0'
    implementation 'com.sangcomz:FishBun:0.8.6'
    implementation 'com.squareup.picasso:picasso:2.5.2'
    implementation 'com.github.bumptech.glide:glide:4.5.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.10.0'
    implementation 'com.github.esafirm.android-image-picker:imagepicker:1.13.1'
    implementation 'com.github.esafirm.android-image-picker:rximagepicker:1.13.1'
    implementation 'androidx.multidex:multidex:2.0.1'
    implementation 'com.makeramen:roundedimageview:2.3.0'
    // implementation 'uk.co.chrisjenx:calligraphy:2.2.0'
    implementation 'com.squareup.picasso:picasso:2.5.2'
    implementation 'com.orhanobut:dialogplus:1.11@aar'
    implementation 'jp.co.cyberagent.android.gpuimage:gpuimage-library:1.3.0'
    implementation 'me.relex:circleindicator:1.2.2@aar'
    implementation 'com.eftimoff:android-viewpager-transformers:1.0.1@aar'
    implementation 'me.hammarstrom.fanmenu:fanmenu:1.0'

    implementation 'io.github.inflationx:calligraphy3:3.1.1'
    implementation 'io.github.inflationx:viewpump:2.0.3'

    androidTestImplementation 'androidx.test:runner:1.2.0'
    // androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
    implementation 'com.squareup.retrofit2:adapter-rxjava2:2.9.0'

    implementation 'uk.co.samuelwall:material-tap-target-prompt:2.14.0'
    implementation 'com.github.florent37:tutoshowcase:1.0.0'
    implementation 'com.github.PhilJay:MPAndroidChart:v3.1.0'
    implementation 'com.flaviofaria:kenburnsview:1.0.7'
    implementation 'org.osmdroid:osmdroid-android:6.1.0'

    implementation 'com.github.MKergall:osmbonuspack:6.6.0'

    implementation 'com.squareup.retrofit2:retrofit:2.3.0'
    implementation 'com.squareup.retrofit2:converter-scalars:2.3.0'
    implementation 'com.facebook.fresco:fresco:1.5.0'
    implementation 'com.journeyapps:zxing-android-embedded:3.4.0'
    implementation 'me.dm7.barcodescanner:zbar:1.9.8'
    implementation 'me.dm7.barcodescanner:zxing:1.9.8'
    implementation 'com.google.code.gson:gson:2.8.5'

    implementation 'com.github.AnyChart:AnyChart-Android:1.1.2'

    implementation 'com.bikomobile:donutprogress:1.2.0'
    implementation 'com.github.lzyzsd:circleprogress:1.2.1'
    implementation('com.github.thekhaeng:pushdown-anim-click:1.1.1') {
        exclude group: 'com.androidx'
    }
    implementation 'com.google.android.material:material:1.2.0'
    implementation 'androidx.core:core:1.3.0'
    implementation 'com.daimajia.easing:library:2.1@aar'
    implementation 'com.daimajia.androidanimations:library:2.3@aar'
    implementation 'com.philliphsu:bottomsheetpickers:2.4.1'
    // implementation 'com.github.captain-miao:optroundcardview:1.0.0'
    implementation 'pl.droidsonroids.gif:android-gif-drawable:1.2.12'

    //implementation 'com.felipecsl:gifimageview:2.2.0'
    implementation 'com.makeramen:roundedimageview:2.3.0'
    implementation 'com.github.nkzawa:socket.io-client:0.3.0'
    implementation 'com.numetriclabz.numandroidcharts:numandroidcharts:1.0.4'
    implementation 'jp.wasabeef:blurry:3.0.0'
    implementation 'org.greenrobot:eventbus:3.1.1'
    implementation 'com.tbuonomo.andrui:viewpagerdotsindicator:2.0.3'
    implementation 'net.alhazmy13.MediaPicker:libary:2.4.4'
    implementation 'com.nabinbhandari.android:permissions:3.7'
    implementation 'com.robinhood.spark:spark:1.2.0'
    implementation 'com.github.anastr:speedviewlib:1.3.1'
    implementation 'com.yarolegovich:discrete-scrollview:1.4.9'
    implementation "org.java-websocket:Java-WebSocket:1.4.0"
    implementation 'com.neovisionaries:nv-websocket-client:2.8'
    implementation 'com.squareup.okhttp3:okhttp:3.14.9'
    implementation files('libs/map_sdk_2.1.jar')

    implementation 'com.android.volley:volley:1.1.1'

    implementation 'com.eyalbira.loadingdots:loading-dots:1.0.2'

    implementation('me.rishabhkhanna:RecyclerviewSwipeDrag:1.3.1') {
        exclude group: 'com.android.support', module: 'recyclerview-v7'
    }

    apply plugin: 'com.google.gms.google-services'
    apply plugin: 'maven'

    googleServices { disableVersionCheck = true }
    implementation 'com.github.hadiidbouk:ChartProgressBar-Android:2.0.6'

}
`

`// Top-level build file where you can add configuration options common to all sub-projects/modules.

// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        google()
        jcenter()
        maven { url 'https://maven.fabric.io/public' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.1'
        classpath 'com.google.gms:google-services:4.2.0'
        classpath 'io.fabric.tools:gradle:1.31.2'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        mavenLocal()

        /* gradle.projectsEvaluated {
             tasks.withType(JavaCompile) {
                 options.compilerArgs << "-Xlint:deprecation"
             }
         }*/
    }
}
task clean(type: Delete) {
    delete rootProject.buildDir
}`

`buildscript {
    repositories {
        jcenter()
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.1'
        classpath 'com.google.gms:google-services:4.2.0'

    }
}

apply plugin: 'com.android.library'
apply plugin: 'maven'
apply plugin: 'signing'

archivesBaseName = 'android-maps-utils'
group = 'com.google.maps.android'

dependencies {

    implementation 'com.google.android.gms:play-services-maps:16.1.0'
}

android {
    compileSdkVersion 29

    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = ['src']
            res.srcDirs = ['res']
        }

        androidTest {
            java.srcDirs = ['tests/src']
        }
    }
    defaultConfig {
        minSdkVersion 20
    }
    buildToolsVersion '29.0.1'
}

task instrumentTest(dependsOn: connectedCheck)

task apklib(type: Zip) {
    dependsOn 'packageReleaseJar'
    appendix = extension = 'apklib'

    from 'AndroidManifest.xml'
    into('res') {
        from 'res'
    }
    into('src') {
        from 'src'
    }
}

artifacts {
    archives apklib
}

signing {
    sign configurations.archives
}

uploadArchives {
    repositories {
        mavenDeployer {
            beforeDeployment { MavenDeployment deployment -> signing.signPom(deployment) }

            repository(url: 'https://oss.sonatype.org/service/local/staging/deploy/maven2') {
//                authentication(userName: sonatypeUsername, password: sonatypePassword)
            }
            snapshotRepository(url: 'https://oss.sonatype.org/content/repositories/snapshots/') {
                //       authentication(userName: sonatypeUsername, password: sonatypePassword)
            }

            modifyPom(addFilter('aar') { artifact, file ->
                artifact.name == 'android-maps-utils'
            })

            modifyPom(addFilter('apklib') { artifact, file ->
                artifact.name == 'android-maps-utils-apklib'
            })

            // There's no official apklib for Google Play services, so we
            // can't really maintain that dependency for the apklib packaging.
            pom('apklib').whenConfigured { pom ->
                pom.dependencies = []
            }
        }
    }
}

def modifyPom(pom) {
    pom.project {
        name 'Google Maps Android API utility library'
        description 'Handy extensions to the Google Maps Android API.'
        url 'https://github.com/googlemaps/android-maps-utils'

        scm {
            url 'scm:git@github.com:googlemaps/android-maps-utils.git'
            connection 'scm:git@github.com:googlemaps/android-maps-utils.git'
            developerConnection 'scm:git@github.com:googlemaps/android-maps-utils.git'
        }

        licenses {
            license {
                name 'The Apache Software License, Version 2.0'
                url 'http://www.apache.org/licenses/LICENSE-2.0.txt'
                distribution 'repo'
            }
        }

        organization {
            name 'Google Inc'
            url 'http://developers.google.com/maps'
        }

        developers {
            developer {
                id 'broady'
                name 'Chris Broadfoot'
                url 'http://google.com/+ChristopherBroadfoot'
            }
        }
    }
}
`

**Comment by Saksham66** [comment]
@Guruvendra 
Please check if you have added these rules to your proguard file
-keep class com.mmi.services.account.** {
    <fields>;
    <methods>;
}
-keep class com.mmi.services.api.** {
    <fields>;
    <methods>;
}
-keep class com.mmi.services.utils.** {
    <fields>;
    <methods>;
}
