### ISSUE TITLE
Flutter SDK

### ISSUE THREAD

**Issue by epsi95** [MapmyIndia/mapmyindia-maps-vectorSDK-android#5]
Is there any plan for Flutter(Dart) SDK, when MMI is going to launch Flutter SDK?

**Comment by sudo-saksham** [comment]
Yes, I'm also facing problem in integrating MMI in flutter application. Please, launch this for Flutter SDK too.

**Comment by kunalbharti** [comment]
Flutter SDK is in the works @MapmyIndia. It is expected to be launched in another couple of months. The roadmap is for the end of this quarter.
We have a pre-release alpha version already live on pub.dev (however, we are working on the docs; so there is no reference/guide available)
If possible, please have a look and provide your feedback.
