### ISSUE TITLE
E/onMapError: 401----SDK not initialised

### ISSUE THREAD

**Issue by romilsingh** [MapmyIndia/mapmyindia-maps-vectorSDK-android#7]
I have already initialised the SDK with the below code.

`MapmyIndiaAccountManager.getInstance().setRestAPIKey("key");
        MapmyIndiaAccountManager.getInstance().setMapSDKKey("key");
        MapmyIndiaAccountManager.getInstance().setAtlasClientId("client_id");
        MapmyIndiaAccountManager.getInstance().setAtlasClientSecret("client_secret");
        MapmyIndia.getInstance(getApplicationContext());`

I have also put the correct keys from the dashboard.

**Comment by kunalbharti** [comment]
@romilsingh 
Please mail to [API Support](mailto:apisupport@mapmyindia.com) with any one of your credentials and let the team know about the issue you are facing. It seems to a minor configuration issue with your access credentials.
Team would be able to resolve the same once they identify your credentials - email used to sign up for MapmyIndia APIs or any 1 of your keys.

**Comment by muankit** [comment]
@romilsingh Is your issue resolved ... i am facing the same
